#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 30 09:34:34 2023

@author: awidmer
"""

import networkx as nx
import matplotlib.pyplot as plt
import csv

# Creer le graphe a partir d'un fichier CSV
G = nx.Graph()
with open('chemins.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # sauter l'en-tete
    for row in reader:
        ville_depart, ville_arrivee, type_t, temps_parcours, cout, distance = row[:6]
        G.add_edge(ville_depart, ville_arrivee, temps_parcours=float(temps_parcours), cout=float(cout), distance=float(distance))

# Definir la disposition du graphe
pos = nx.spring_layout(G)

# Dessiner les noeuds et les aretes du graphe
nx.draw_networkx_nodes(G, pos, node_size=500, node_color='lightblue')
nx.draw_networkx_edges(G, pos, width=2, edge_color='blue')

# Ajouter des etiquettes aux noeuds
labels = {}
for node in G.nodes():
    labels[node] = node
nx.draw_networkx_labels(G, pos, labels, font_size=10)

# Afficher le graphe
plt.axis('off')
plt.show()
